// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxmoxt-K5LRAUIzQ_zRw2ygbcXrjesWGg',
    appId: '1:791507240909:web:4507a01074ddfb2c9ce684',
    messagingSenderId: '791507240909',
    projectId: 'cityfix-j1710',
    authDomain: 'cityfix-j1710.firebaseapp.com',
    storageBucket: 'cityfix-j1710.firebasestorage.app',
    measurementId: 'G-34L0608LCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBskHRP-OfY9Y5K_5alLm0H6K5iSd3VHSc',
    appId: '1:791507240909:android:84234033f05f1e5f9ce684',
    messagingSenderId: '791507240909',
    projectId: 'cityfix-j1710',
    storageBucket: 'cityfix-j1710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrMGvUPTiJXDqS0Cyr27ybqW_V8xD8yZk',
    appId: '1:791507240909:ios:e7c0f6f89c084d029ce684',
    messagingSenderId: '791507240909',
    projectId: 'cityfix-j1710',
    storageBucket: 'cityfix-j1710.firebasestorage.app',
    iosBundleId: 'com.project.cityfix.cityfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrMGvUPTiJXDqS0Cyr27ybqW_V8xD8yZk',
    appId: '1:791507240909:ios:e7c0f6f89c084d029ce684',
    messagingSenderId: '791507240909',
    projectId: 'cityfix-j1710',
    storageBucket: 'cityfix-j1710.firebasestorage.app',
    iosBundleId: 'com.project.cityfix.cityfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxmoxt-K5LRAUIzQ_zRw2ygbcXrjesWGg',
    appId: '1:791507240909:web:9b6d0d05f40213a89ce684',
    messagingSenderId: '791507240909',
    projectId: 'cityfix-j1710',
    authDomain: 'cityfix-j1710.firebaseapp.com',
    storageBucket: 'cityfix-j1710.firebasestorage.app',
    measurementId: 'G-RX1GNPBLWK',
  );
}
